sqlite3:
  :adapter: sqlite3
  :dbfile: spec/db/reports_as_sparkline.sqlite3.db

mysql:
  adapter: mysql
  database: reports_as_sparkline_test
  username: reports_as_spark
  password: reports_as_spark
  host: localhost
  