sqlite3:
  adapter:  sqlite3
  database: spec/db/reportable.sqlite3.db
mysql:
  adapter:  mysql
  database: reportable_test
  username: reportable
  password: reportable
  host:     localhost
postgresql:
  adapter:  postgresql
  database: reportable_test
  username: reportable
  password: reportable
  host:     localhost